'use strict';
const $=id=>document.getElementById(id);
const FILE_LIMIT=10*1024*1024;
const notes={india_categorical:'Full 266-isolate Indian study. Categorical AST: nominal S/I/R/SDD/missing. Meropenem audit retains 213 isolates (198 R / 15 S). Standard/version and patient IDs are not supplied; class-balance gates block training.',demo:'Generated fixture only. Any apparent performance is software behavior, never biological evidence.',public:'1,804 public BioSamples; 25,387 AST rows. Earlier audit: 499 eligible. Patient IDs and mechanism annotations unavailable.',india:'Two public BioSamples; 29 AST rows. One eligible resistant isolate and no eligible susceptible isolate. Audit is available; training must be blocked.',upload:'Use de-identified, authorized source files. Files are processed on this device; download outputs before closing the tab.'};
let operation=0;
let worker, busy=false,modelReady=false,bundle=null,report=null,networkBundle=null,currentResult=null;
function status(message,error=false){$('status').textContent=message;$('status').classList.toggle('error',error);}
function log(message){const lines=$('logs').textContent.split('\n').slice(-80);lines.push(message);$('logs').textContent=lines.join('\n');}
function table(records,cols){if(!records?.length)return '<p class="hint">No rows available.</p>';const keys=cols||[...new Set(records.flatMap(r=>Object.keys(r)))];return '<div class="table-scroll"><table><thead><tr>'+keys.map(k=>'<th>'+escape(k)+'</th>').join('')+'</tr></thead><tbody>'+records.map(r=>'<tr>'+keys.map(k=>'<td>'+escape(typeof r[k]==='object'?JSON.stringify(r[k]):r[k]??'—')+'</td>').join('')+'</tr>').join('')+'</tbody></table></div>';}
function escape(value){return String(value).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
function sync(){for(const id of ['interpretation-standard','interpretation-version','comparability-policy','representation','target-drug','validate','validation-mode','heldout-value','source-split','dataset','configuration','audit','train','breakpoints','genes','geography'])$(id).disabled=busy;$('observations').disabled=busy||$('dataset').value!=='upload';$('cancel').disabled=!busy;$('progress').hidden=!busy;$('predict-button').disabled=busy||!modelReady;$('topology-button').disabled=busy||!modelReady;$('download').disabled=busy||!bundle;$('report-download').disabled=busy||!report;$('topology-download').disabled=busy||!networkBundle;}
async function textFile(input){const f=input.files[0];if(!f)return '';if(f.size>FILE_LIMIT)throw Error('CSV limit is 10 MB. Use the downloadable Python pipeline for larger cohorts.');return f.text();}
async function asset(path){const response=await fetch(path);if(!response.ok)throw Error('Could not load '+path);return response.text();}
async function setDataset(){const kind=$('dataset').value;$('dataset-note').textContent=notes[kind];try{$('configuration').value=await asset('configs/'+(kind==='demo'?'demo':kind==='india_categorical'?'india_categorical':'public_pilot')+'.json');if(kind==='upload'){const cfg=JSON.parse($('configuration').value);cfg.allow_unversioned_reported=false;cfg.bootstrap_repeats=200;$('configuration').value=JSON.stringify(cfg,null,2);}syncDesign();modelReady=false;sync();}catch(e){status(e.message,true);}}
function createWorker(){if(worker)return worker;worker=new Worker('worker.js');worker.onmessage=({data})=>{if(data.type==='progress'){log(data.message);status(data.message);return;}busy=false;if(data.type==='error'){status(data.message,true);log(data.message);modelReady=false;worker.terminate();worker=null;sync();return;}const r=data.result;if(r.action==='predict'){ $('prediction').textContent=`Estimated probability of resistance: ${(r.probability*100).toFixed(1)}%. Decision: ${r.decision.replaceAll('_',' ')}. ${r.evidence_status}. Research only; clinical accuracy is not established.`;status('Research prediction complete.');}
else if(r.action==='topology'){networkBundle=r.archive;$('topology-result').innerHTML='<p>'+escape(r.analysis)+'</p>'+['genes','geography'].filter(k=>r[k]).map(k=>'<h3>'+escape(k)+' — '+r[k].edges+' pair rows</h3>'+table(r[k].preview)).join('');status('Development-only network tables complete.');}
else{currentResult=r;bundle=r.archive;report=r.report;modelReady=!!r.metrics;networkBundle=null;$('topology-result').textContent='Supply documented annotations for this model’s training isolates.';render(r);status(r.blocked?'Training blocked: '+r.blocked:r.suite?'Validation suite complete. Review every evaluated and blocked source.':r.metrics?'Experiment complete. Inspect operating-point performance and uncertainty.':'Audit complete. Review exclusions before training.',!!r.blocked);if(modelReady)setupPrediction(r);}
sync();};worker.onerror=e=>{busy=false;modelReady=false;status('Runtime error: '+e.message,true);worker.terminate();worker=null;sync();};return worker;}
async function launch(action){const task=++operation;try{busy=true;sync();status('Preparing source data…');let payload={action};if(action==='audit'||action==='train'||action==='validate'){const kind=$('dataset').value;const csv=kind==='upload'?await textFile($('observations')):await asset('data/'+kind+'.csv');if(!csv)throw Error('Choose an observations CSV first.');JSON.parse($('configuration').value);payload={action,csv,configuration:$('configuration').value,breakpoints:await textFile($('breakpoints'))};modelReady=false;bundle=null;report=null;$('report').hidden=true;$('run-summary').textContent='Running '+action+' on the selected source data…';$('metrics').textContent='';$('logs').textContent='';}
if(action==='predict'){payload.species=$('species').value;payload.values={};for(const drug of currentResult.features)payload.values[drug]={value:$('value-'+drug).value,operator:$('op-'+drug)?.value||'='};}
if(action==='topology'){payload.genes=await textFile($('genes'));payload.geography=await textFile($('geography'));if(!payload.genes&&!payload.geography)throw Error('Choose a gene or geography CSV first.');}
if(task!==operation)return;createWorker().postMessage(payload);sync();}catch(e){busy=false;status(e.message,true);sync();}}
function render(r){const a=r.audit;$('run-summary').innerHTML='<strong>'+escape(a.evidence_status)+'</strong><p>'+a.eligible_isolates+' eligible of '+a.raw_isolates+' input isolates · '+a.raw_rows+' AST rows · '+a.patient_ids_available+' patient IDs available.</p>'+table(Object.entries(a.excluded_event_counts).map(([reason,events])=>({reason,events})))+'<p class="hint">Exclusion events can include feature-level events; they are not unique excluded isolates.</p>'+'<h3>Laboratory comparability</h3><p>'+escape(a.comparability?.status||'Not assessed')+'</p>'+table(Object.entries(a.comparability?.missing_provenance_rows||{}).map(([field,rows])=>({field,missing_rows:rows})))+'<p class="hint">No lab-specific scaling is applied. Provenance checks do not establish measurement agreement or India accuracy.</p><h3>Country coverage</h3>'+table(r.countries)+'<h3>Source coverage</h3>'+table(r.sources)+ (r.blocked?'<div class="notice"><strong>Training blocked</strong>'+escape(r.blocked)+'</div>':'');
$('preview').innerHTML=table(r.preview,['isolate_id','source_id','country','species','mechanism','target_sir','observed_features']);$('preview-wrap').hidden=false;
if(r.suite){$('metrics').innerHTML='<h3>All-source validation</h3><p>Every available source was attempted. Blocked experiments remain visible. No test-selected winner; India validation remains unestablished.</p>'+table(r.suite.experiments,['kind','heldout','experiment_eligible_n','status','n','sensitivity','specificity','fn','fp','reason']);}
if(r.metrics){const m=r.metrics;const value=v=>v==null?'—':Number(v).toFixed(3);$('metrics').innerHTML='<div class="metrics-grid">'+[['AUROC',m.auroc],['SENSITIVITY',m.sensitivity],['SPECIFICITY',m.specificity],['BRIER SCORE',m.brier]].map(([k,v])=>'<div class="metric"><small>'+k+'</small><strong>'+value(v)+'</strong></div>').join('')+'</div><div class="notice"><strong>'+escape(a.synthetic?'Synthetic fixture — software check':m.interpretation_status==='OPERATING_POINT_FAILED'?'Research operating targets not met':'Exploratory operating point — not validated')+'</strong>'+m.fn+' false negatives; '+m.fp+' false positives among '+m.n+' test isolates. Selected model: '+escape(m.selected_model)+'. Split: '+escape(m.split_mode)+'. '+(m.small_sample_warning?'Small outcome groups; inspect bootstrap intervals. ':'')+'No independent external or clinical validation.</div><p>All eligible isolates used: '+(m.all_eligible_isolates_used?'yes':'inspect manifest')+'. India test isolates: '+m.india_test_isolates+'.</p>'+table(Object.entries(m.partition_counts).map(([partition,isolates])=>({partition,isolates})))+'<h3>Development model comparison</h3>'+table(r.comparison,['model','log_loss','auroc','brier','phase']);}
$('report').srcdoc=r.report;$('report').hidden=false;}
function setupPrediction(r){const cfg=JSON.parse($('configuration').value);$('species').replaceChildren(...r.species.map(s=>{const option=document.createElement('option');option.textContent=s;return option;}));$('mic-inputs').innerHTML=r.features.map(d=>cfg.representation==='categorical_ast'?'<div><label for="value-'+escape(d)+'">'+escape(d)+' (reported AST)</label><select id="value-'+escape(d)+'">'+[['','Missing / not tested'],['S','S'],['I','I'],['R','R'],['SDD','SDD']].map(([v,label])=>'<option value="'+v+'">'+label+'</option>').join('')+'</select></div>':'<div><label for="value-'+escape(d)+'">'+escape(d)+' (mg/L)</label><div class="mic-row"><select id="op-'+escape(d)+'" aria-label="'+escape(d)+' censoring operator">'+['=','<=','>=','<','>'].map(op=>'<option>'+escape(op)+'</option>').join('')+'</select><input id="value-'+escape(d)+'" type="number" min="0.000001" max="1024" step="any" placeholder="Missing"></div></div>').join('');$('prediction').textContent='Session model ready. Enter independently measured '+(cfg.representation==='categorical_ast'?'AST categories':'MICs')+'; minimum panel: '+cfg.min_observed_features+'.';}
function download(content,name,type='application/zip',base64=true){const data=base64?Uint8Array.from(atob(content),c=>c.charCodeAt(0)):content;const url=URL.createObjectURL(new Blob([data],{type}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
$('configuration').addEventListener('input',()=>{modelReady=false;sync();});
$('dataset').addEventListener('change',setDataset);$('audit').onclick=()=>launch('audit');$('train').onclick=()=>launch('train');$('validate').onclick=()=>launch('validate');$('predict-button').onclick=()=>launch('predict');$('topology-button').onclick=()=>launch('topology');$('cancel').onclick=()=>{operation++;worker?.terminate();worker=null;busy=false;modelReady=false;status('Stopped. The interrupted session model has been discarded.');sync();};$('download').onclick=()=>download(bundle,'amr-experiment-'+new Date().toISOString().slice(0,10)+'.zip');$('report-download').onclick=()=>download(report,'amr-report.html','text/html',false);$('topology-download').onclick=()=>download(networkBundle,'amr-development-networks.zip');setDataset();

$("source-split").onclick=async()=>{if(busy)return;$("dataset").value="public";await setDataset();$("configuration").value=await asset("configs/public_source_holdout.json");syncDesign();status("Public source-held-out configuration loaded. This is an exploratory challenge; inspect failure outcomes.");};

function syncDesign(){const cfg=JSON.parse($('configuration').value);$('interpretation-standard').value=cfg.standard;$('interpretation-version').value=cfg.standard_version||'';$('comparability-policy').value=cfg.comparability_policy||'exploratory';$('representation').value=cfg.representation||'mic';$('target-drug').value=cfg.target;$('validation-mode').value=cfg.split.mode;$('heldout-value').value=(cfg.split.heldout||[]).join(', ');}
function updateDesign(){try{const cfg=JSON.parse($('configuration').value);cfg.split={mode:$('validation-mode').value};if(cfg.split.mode==='source')cfg.require_known_source=true;if(cfg.split.mode!=='internal')cfg.split.heldout=$('heldout-value').value.split(',').map(s=>s.trim()).filter(Boolean);$('configuration').value=JSON.stringify(cfg,null,2);modelReady=false;sync();}catch(e){status(e.message,true);}}
$('validation-mode').onchange=updateDesign;$('heldout-value').onchange=updateDesign;

function updateModelDesign(){try{const cfg=JSON.parse($("configuration").value);cfg.representation=$("representation").value;cfg.target=$("target-drug").value;if(cfg.representation==="categorical_ast")cfg.label_mode="reported";$("configuration").value=JSON.stringify(cfg,null,2);modelReady=false;sync();status("Model design updated. Audit the complete cohort before training.");}catch(e){status(e.message,true);}}
$("representation").onchange=updateModelDesign;$("target-drug").onchange=updateModelDesign;

$("configuration").addEventListener("input",()=>{modelReady=false;sync();});
$("configuration").addEventListener("change",()=>{try{syncDesign();}catch(e){status("Configuration JSON is incomplete or invalid.",true);}});

$('comparability-policy').onchange=()=>{try{const cfg=JSON.parse($('configuration').value);cfg.comparability_policy=$('comparability-policy').value;$('configuration').value=JSON.stringify(cfg,null,2);modelReady=false;sync();status(cfg.comparability_policy==='strict'?'Strict provenance enabled. Set the documented EUCAST/CLSI standard_version in the configuration, then audit.':'Exploratory mode enabled. Provenance gaps remain visible.');}catch(e){status(e.message,true);}};

function updateInterpretation(){try{const cfg=JSON.parse($('configuration').value);cfg.standard=$('interpretation-standard').value;const version=$('interpretation-version').value.trim();if(version)cfg.standard_version=version;else delete cfg.standard_version;$('configuration').value=JSON.stringify(cfg,null,2);modelReady=false;sync();status('Interpretation filter updated. Audit again; historical labels are not automatically converted.');}catch(e){status(e.message,true);}}
$('interpretation-standard').onchange=updateInterpretation;$('interpretation-version').onchange=updateInterpretation;
