'use strict';
const $=id=>document.getElementById(id);
const FILE_LIMIT=10*1024*1024;
const notes={india_categorical:'Full 266-isolate Indian study. Categorical AST: nominal S/I/R/SDD/missing. Meropenem audit retains 213 isolates (198 R / 15 S). Standard/version and patient IDs are not supplied; class-balance gates block training.',demo:'Generated fixture only. Any apparent performance is software behavior, never biological evidence.',public:'1,804 public BioSamples; 25,387 AST rows. Earlier audit: 499 eligible. Patient IDs and mechanism annotations unavailable.',india:'Two public BioSamples; 29 AST rows. One eligible resistant isolate and no eligible susceptible isolate. Audit is available; training must be blocked.',upload:'Use de-identified, authorized source files. Files are processed on this device; download outputs before closing the tab.'};
let operation=0;
let preparedCsv=null,batchManifest=null;
let datasetGeneration=0;
function invalidateSession(){modelReady=false;currentResult=null;preparedCsv=null;batchManifest=null;bundle=null;report=null;networkBundle=null;if($('batch-status'))$('batch-status').textContent='Inputs changed. Prepare a new batch or audit the current file.';if($('prediction'))$('prediction').textContent='Settings or source changed. Audit and train again before predicting.';if($('metrics'))$('metrics').textContent='';if($('run-summary'))$('run-summary').textContent='Source or settings changed. Audit and train a new experiment.';if($('report'))$('report').hidden=true;}
let worker, busy=false,modelReady=false,bundle=null,report=null,networkBundle=null,currentResult=null;
function status(message,error=false){$('status').textContent=message;$('status').classList.toggle('error',error);}
function log(message){const lines=$('logs').textContent.split('\n').slice(-80);lines.push(message);$('logs').textContent=lines.join('\n');}
const tablePages=new Map();let tableSequence=0;
function table(records,cols,page=0,tableId=null){if(!records?.length)return '<p class="hint">No rows available.</p>';const keys=cols||[...new Set(records.flatMap(r=>Object.keys(r)))];const id=tableId||String(++tableSequence);tablePages.set(id,{records,keys});const start=page*25;const controls=records.length>25?'<div class="table-pages"><span role="status">Rows '+(start+1)+'–'+Math.min(start+25,records.length)+' of '+records.length+'. Complete data in the experiment export.</span><button type="button" data-table="'+id+'" data-page="'+(page-1)+'" '+(page===0?'disabled':'')+'>Previous</button><button type="button" data-table="'+id+'" data-page="'+(page+1)+'" '+(start+25>=records.length?'disabled':'')+'>Next</button></div>':'';return '<div data-table-host="'+id+'">'+controls+ '<div class="table-scroll"><table><thead><tr>'+keys.map(k=>'<th>'+escape(k)+'</th>').join('')+'</tr></thead><tbody>'+records.slice(start,start+25).map(r=>'<tr>'+keys.map(k=>'<td>'+escape(typeof r[k]==='object'?JSON.stringify(r[k]):r[k]??'—')+'</td>').join('')+'</tr>').join('')+'</tbody></table></div></div>';}
document.addEventListener('click',e=>{const button=e.target.closest('button[data-table]');if(!button)return;const entry=tablePages.get(button.dataset.table);if(!entry)return;const host=button.closest('[data-table-host]');host.outerHTML=table(entry.records,entry.keys,Number(button.dataset.page),button.dataset.table);document.querySelector('[data-table-host="'+button.dataset.table+'"] button:not(:disabled)')?.focus({preventScroll:true});});
function escape(value){return String(value).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
function sync(){for(const id of ['panel-drugs','panel-min','panel-coverage','panel-max','include-species','sensitivity-goal','threshold-policy','decision-policy','framework-mode','interpretation-standard','interpretation-version','comparability-policy','representation','target-drug','validate','validation-mode','heldout-value','source-split','dataset','configuration','audit','train','breakpoints','genes','geography'])$(id).disabled=busy;$('observations').disabled=busy||$('dataset').value!=='upload';$('cancel').disabled=!busy;$('progress').hidden=!busy;$('predict-button').disabled=busy||!modelReady;$('topology-button').disabled=busy||!modelReady;$('download').disabled=busy||!bundle;$('report-download').disabled=busy||!report;$('topology-download').disabled=busy||!networkBundle;$('baseline').disabled=busy||$('dataset').value!=='upload';$('prepare-batch').disabled=busy||$('dataset').value!=='upload';$('batch-download').disabled=busy||!preparedCsv;$('manifest-download').disabled=busy||!batchManifest;document.dispatchEvent(new CustomEvent('amr:state',{detail:{busy,modelReady,result:currentResult}}));}
async function textFile(input){const f=input.files[0];if(!f)return '';if(f.size>FILE_LIMIT)throw Error('CSV limit is 10 MB. Use the downloadable Python pipeline for larger cohorts.');return f.text();}
async function asset(path){const response=await fetch(path);if(!response.ok)throw Error('Could not load '+path);return response.text();}
async function setDataset(){const generation=++datasetGeneration;const kind=$('dataset').value;invalidateSession();$('dataset-note').textContent=notes[kind];try{const configText=await asset('configs/'+(kind==='demo'?'demo':kind==='india_categorical'?'india_categorical':'framework_browser')+'.json');if(generation!==datasetGeneration)return;$('configuration').value=configText;if(kind==='upload'){const cfg=JSON.parse($('configuration').value);cfg.allow_unversioned_reported=false;cfg.bootstrap_repeats=200;cfg.split={mode:'internal'};$('configuration').value=JSON.stringify(cfg,null,2);}syncDesign();invalidateSession();sync();}catch(e){status(e.message,true);}}
function createWorker(){if(worker)return worker;worker=new Worker('worker.js');worker.onmessage=({data})=>{if(data.type==='progress'){log(data.message);status(data.message);return;}busy=false;if(data.type==='error'){status(data.message,true);log(data.message);modelReady=false;worker.terminate();worker=null;sync();return;}const r=data.result;if(r.action==='prepare'){preparedCsv=r.csv;batchManifest=r.manifest;currentResult=null;modelReady=false;$('batch-status').textContent=`Prepared ${r.manifest.rows} rows across ${r.manifest.isolate_source_pairs} source/isolate pairs. Removed ${r.manifest.exact_duplicate_rows_removed} exact duplicates. This combined file will be used for the next audit. Save the CSV and manifest, then audit.`;status('Batch prepared, not audited. Audit the combined observations before training.');}
else if(r.action==='predict'){ $('prediction').textContent=`Estimated probability of resistance: ${(r.probability*100).toFixed(1)}%. Decision: ${r.decision.replaceAll('_',' ')}. ${r.evidence_status}. ${r.interpretation_status}. Research only; clinical accuracy is not established.`;status('Research prediction complete.');}
else if(r.action==='topology'){networkBundle=r.archive;$('topology-result').innerHTML='<p>'+escape(r.analysis)+'</p>'+['genes','geography'].filter(k=>r[k]).map(k=>'<h3>'+escape(k)+' — '+r[k].edges+' pair rows</h3>'+table(r[k].preview)).join('');status('Development-only network tables complete.');}
else{currentResult=r;bundle=r.archive;report=r.report;modelReady=!!r.metrics;networkBundle=null;$('topology-result').textContent='Supply documented annotations for this model’s training isolates.';render(r);status(r.blocked?'Training blocked: '+r.blocked:r.suite?'Validation suite complete. Review every evaluated and blocked source.':r.metrics?'Experiment complete. Inspect operating-point performance and uncertainty.':'Audit complete. Review exclusions before training.',!!r.blocked);if(modelReady)setupPrediction(r);}
sync();};worker.onerror=e=>{busy=false;modelReady=false;status('Runtime error: '+e.message,true);worker.terminate();worker=null;sync();};return worker;}
async function launch(action){const task=++operation;try{busy=true;sync();status('Preparing source data…');let payload={action};if(action==='prepare'){invalidateSession();payload={action,csv:await textFile($('observations')),base_csv:await textFile($('baseline'))};}
if(action==='audit'||action==='train'||action==='validate'){const kind=$('dataset').value;const csv=kind==='upload'?(preparedCsv||await textFile($('observations'))):await asset('data/'+kind+'.csv');if(!csv)throw Error('Choose an observations CSV first.');JSON.parse($('configuration').value);payload={action,csv,configuration:$('configuration').value,breakpoints:await textFile($('breakpoints'))};modelReady=false;currentResult=null;bundle=null;report=null;networkBundle=null;$('report').hidden=true;$('run-summary').textContent='Running '+action+' on the selected source data…';$('metrics').textContent='';$('logs').textContent='';}
if(action==='predict'){payload.species=$('species').value;payload.values={};for(const drug of currentResult.features)payload.values[drug]={value:$('value-'+drug).value,operator:$('op-'+drug)?.value||'='};}
if(action==='topology'){payload.genes=await textFile($('genes'));payload.geography=await textFile($('geography'));if(!payload.genes&&!payload.geography)throw Error('Choose a gene or geography CSV first.');}
if(task!==operation)return;createWorker().postMessage(payload);sync();}catch(e){busy=false;status(e.message,true);sync();}}
function render(r){tablePages.clear();const a=r.audit;$('run-summary').innerHTML='<strong>'+escape(a.evidence_status)+'</strong><p>'+a.eligible_isolates+' eligible of '+a.raw_isolates+' input isolates · '+a.raw_rows+' AST rows · '+a.patient_ids_available+' patient IDs available.</p>'+table(Object.entries(a.excluded_event_counts).map(([reason,events])=>({reason,events})))+'<p class="hint">Exclusion events can include feature-level events; they are not unique excluded isolates.</p>'+'<h3>Laboratory comparability</h3><p>'+escape(a.comparability?.status||'Not assessed')+'</p>'+table(Object.entries(a.comparability?.missing_provenance_rows||{}).map(([field,rows])=>({field,missing_rows:rows})))+'<p class="hint">No lab-specific scaling is applied. Provenance checks do not establish measurement agreement or India accuracy.</p><h3>Antibiotic panel coverage</h3>'+table(a.panel_coverage,['drug','source_id','isolates','observed','coverage'])+'<h3>Country coverage</h3>'+table(r.countries)+'<h3>Source coverage</h3>'+table(r.sources)+ (r.blocked?'<div class="notice"><strong>Training blocked</strong>'+escape(r.blocked)+'</div>':'');
$('preview').innerHTML=table(r.preview,['isolate_id','source_id','country','species','mechanism','target_sir','observed_features']);$('preview-wrap').hidden=false;
if(r.suite){$('metrics').innerHTML='<h3>All-source validation</h3><p>Every available source was attempted. Blocked experiments remain visible. No test-selected winner; India validation remains unestablished.</p>'+table(r.suite.experiments,['kind','heldout','experiment_eligible_n','status','n','sensitivity','specificity','fn','fp','reason']);}
if(r.metrics){const m=r.metrics;const value=v=>v==null?'—':Number(v).toFixed(3);$('metrics').innerHTML='<div class="metrics-grid">'+[['AUROC',m.auroc],['SENSITIVITY',m.sensitivity],['SPECIFICITY',m.specificity],['BRIER SCORE',m.brier]].map(([k,v])=>'<div class="metric"><small>'+k+'</small><strong>'+value(v)+'</strong></div>').join('')+'</div><div class="notice"><strong>'+escape(a.synthetic?'Synthetic fixture — software check':m.interpretation_status==='OPERATING_POINT_FAILED'?'Research operating targets not met':'Exploratory operating point — not validated')+'</strong>'+m.fn+' false negatives; '+m.fp+' false positives among '+m.n+' test isolates. Selected model: '+escape(m.selected_model)+'. Split: '+escape(m.split_mode)+'. '+(m.small_sample_warning?'Small outcome groups; inspect exact and cluster intervals. ':'')+'No independent external or clinical validation.</div><p>All eligible isolates used: '+(m.all_eligible_isolates_used?'yes':'inspect manifest')+'. India test isolates: '+m.india_test_isolates+'.</p>'+table(Object.entries(m.partition_counts).map(([partition,isolates])=>({partition,isolates})))+'<h3>95% exact intervals</h3>'+table([{metric:'Sensitivity',...m.sensitivity_exact_95},{metric:'Specificity',...m.specificity_exact_95}],['metric','low','high','n'])+'<p class="hint">Exact intervals assume independent isolates. Cluster bootstrap results are in the report; neither corrects missing patient identities.</p><h3>Development model comparison</h3>'+table(r.comparison,['model','log_loss','auroc','brier','phase']);}
if(r.metrics){$('metrics').innerHTML+='<h3>Selected antibiotic panel</h3><p>'+escape(r.metrics.selected_drugs?.join(', ')||r.features.join(', '))+'</p><h3>Ranked antibiotic importance</h3>'+table(r.importance,['drug','mean_log_loss_increase','repeat_sd','meaning']);}
$('report').srcdoc=r.report;$('report').hidden=false;}
function setupPrediction(r){const cfg=JSON.parse($('configuration').value);$('species').replaceChildren(...r.species.map(s=>{const option=document.createElement('option');option.textContent=s;return option;}));$('mic-inputs').innerHTML=r.features.map(d=>cfg.representation==='categorical_ast'?'<div><label for="value-'+escape(d)+'">'+escape(d)+' (reported AST)</label><select id="value-'+escape(d)+'">'+[['','Missing / not tested'],['S','S'],['I','I'],['R','R'],['SDD','SDD']].map(([v,label])=>'<option value="'+v+'">'+label+'</option>').join('')+'</select></div>':'<div><label for="value-'+escape(d)+'">'+escape(d)+' (mg/L)</label><div class="mic-row"><select id="op-'+escape(d)+'" aria-label="'+escape(d)+' censoring operator">'+['=','<=','>=','<','>'].map(op=>'<option>'+escape(op)+'</option>').join('')+'</select><input id="value-'+escape(d)+'" type="number" min="0.000001" max="1024" step="any" placeholder="Missing"></div></div>').join('');$('prediction').textContent='Session model ready. Enter independently measured '+(cfg.representation==='categorical_ast'?'AST categories':'MICs')+'; minimum panel: '+cfg.min_observed_features+'.';}
function download(content,name,type='application/zip',base64=true){const data=base64?Uint8Array.from(atob(content),c=>c.charCodeAt(0)):content;const url=URL.createObjectURL(new Blob([data],{type}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
$('configuration').addEventListener('input',()=>{invalidateSession();sync();});
$('dataset').addEventListener('change',setDataset);$('audit').onclick=()=>launch('audit');$('train').onclick=()=>launch('train');$('validate').onclick=()=>launch('validate');$('predict-button').onclick=()=>launch('predict');$('topology-button').onclick=()=>launch('topology');$('cancel').onclick=()=>{operation++;worker?.terminate();worker=null;busy=false;invalidateSession();status('Stopped. The interrupted session model has been discarded.');sync();};$('download').onclick=()=>download(bundle,'amr-experiment-'+new Date().toISOString().slice(0,10)+'.zip');$('report-download').onclick=()=>download(report,'amr-report.html','text/html',false);$('topology-download').onclick=()=>download(networkBundle,'amr-development-networks.zip');setDataset();

$("source-split").onclick=async()=>{if(busy)return;$("dataset").value="public";await setDataset();$("configuration").value=await asset("configs/public_source_holdout.json");syncDesign();status("Public source-held-out configuration loaded. This is an exploratory challenge; inspect failure outcomes.");};

function syncDesign(){const cfg=JSON.parse($('configuration').value);$('panel-drugs').value=cfg.features.join(', ');$('panel-min').value=cfg.min_observed_features;$('panel-coverage').value=cfg.feature_selection?.min_coverage??.2;$('panel-max').value=cfg.feature_selection?.max_drugs??'';$('include-species').checked=!!cfg.include_species;$('sensitivity-goal').value=cfg.sensitivity_target??.95;$('threshold-policy').value=cfg.threshold_policy||'calibration';$('decision-policy').value=cfg.decision_policy||'validated_band';$('interpretation-standard').value=cfg.standard;$('interpretation-version').value=cfg.standard_version||'';$('comparability-policy').value=cfg.comparability_policy||'exploratory';$('representation').value=cfg.representation||'mic';$('target-drug').value=cfg.target;$('validation-mode').value=cfg.split.mode;$('heldout-value').value=(cfg.split.heldout||[]).join(', ');}
function updateDesign(){try{const cfg=JSON.parse($('configuration').value);cfg.split={mode:$('validation-mode').value};if(cfg.split.mode==='source')cfg.require_known_source=true;if(cfg.split.mode!=='internal')cfg.split.heldout=$('heldout-value').value.split(',').map(s=>s.trim()).filter(Boolean);$('configuration').value=JSON.stringify(cfg,null,2);invalidateSession();sync();}catch(e){status(e.message,true);}}
$('validation-mode').onchange=updateDesign;$('heldout-value').onchange=updateDesign;

function updateModelDesign(){try{const cfg=JSON.parse($("configuration").value);cfg.representation=$("representation").value;cfg.target=$("target-drug").value;cfg.features=cfg.features.filter(d=>d!==cfg.target&&!d.startsWith(cfg.target+"-")&&!cfg.target.startsWith(d+"-"));if(!["meropenem","imipenem"].includes(cfg.target))cfg.task="antibiotic_resistance";if(cfg.representation==="categorical_ast")cfg.label_mode="reported";$("configuration").value=JSON.stringify(cfg,null,2);invalidateSession();sync();syncDesign();status("Model design updated. Audit the complete cohort before training.");}catch(e){status(e.message,true);}}
$("representation").onchange=updateModelDesign;$("target-drug").onchange=updateModelDesign;


$("configuration").addEventListener("change",()=>{try{syncDesign();}catch(e){status("Configuration JSON is incomplete or invalid.",true);}});

$('comparability-policy').onchange=()=>{try{const cfg=JSON.parse($('configuration').value);cfg.comparability_policy=$('comparability-policy').value;$('configuration').value=JSON.stringify(cfg,null,2);invalidateSession();sync();status(cfg.comparability_policy==='strict'?'Strict provenance enabled. Set the documented EUCAST/CLSI standard_version in the configuration, then audit.':'Exploratory mode enabled. Provenance gaps remain visible.');}catch(e){status(e.message,true);}};

function updateInterpretation(){try{const cfg=JSON.parse($('configuration').value);cfg.standard=$('interpretation-standard').value;const version=$('interpretation-version').value.trim();if(version)cfg.standard_version=version;else delete cfg.standard_version;$('configuration').value=JSON.stringify(cfg,null,2);invalidateSession();sync();status('Interpretation filter updated. Audit again; historical labels are not automatically converted.');}catch(e){status(e.message,true);}}
$('interpretation-standard').onchange=updateInterpretation;$('interpretation-version').onchange=updateInterpretation;

$('framework-mode').onclick=async()=>{try{const cfg=JSON.parse(await asset('configs/framework_browser.json'));const previous=JSON.parse($('configuration').value);for(const key of ['species','standard','standard_version','comparability_policy','allow_unversioned_reported','representation','target','split']){if(key in previous)cfg[key]=previous[key];else delete cfg[key];}cfg.features=cfg.features.filter(d=>d!==cfg.target&&!d.startsWith(cfg.target+'-')&&!cfg.target.startsWith(d+'-'));$('configuration').value=JSON.stringify(cfg,null,2);syncDesign();invalidateSession();sync();status('Broad MIC framework loaded. Dynamic settings are ready. Target MIC is excluded; archived evidence is not performance for this design.');}catch(e){status(e.message,true);}};

function updateDynamicSettings(){try{const cfg=JSON.parse($('configuration').value);cfg.task='antibiotic_resistance';cfg.features=$('panel-drugs').value.split(',').map(s=>s.trim().toLowerCase()).filter(Boolean);cfg.min_observed_features=Number($('panel-min').value);cfg.include_species=$('include-species').checked;cfg.feature_selection={min_coverage:Number($('panel-coverage').value),correlation_threshold:cfg.feature_selection?.correlation_threshold??.95,max_drugs:$('panel-max').value?Number($('panel-max').value):null};cfg.sensitivity_target=Number($('sensitivity-goal').value);cfg.threshold_policy=$('threshold-policy').value;cfg.decision_policy=$('decision-policy').value;cfg.deferral_halfwidth=cfg.decision_policy==='research_binary'?0:.1;$('configuration').value=JSON.stringify(cfg,null,2);invalidateSession();sync();status('Experiment updated. Audit or train to fit a new model; prior session predictions are cleared.');}catch(e){status(e.message,true);}}
for(const id of ['panel-drugs','panel-min','panel-coverage','panel-max','include-species','sensitivity-goal','threshold-policy','decision-policy'])$(id).onchange=updateDynamicSettings;

$('prepare-batch').onclick=()=>launch('prepare');
$('batch-download').onclick=()=>download(preparedCsv,'amr-combined-observations.csv','text/csv',false);
$('manifest-download').onclick=()=>download(JSON.stringify(batchManifest,null,2),'amr-batch-manifest.json','application/json',false);
for(const id of ['observations','baseline','breakpoints'])$(id).addEventListener('change',()=>{invalidateSession();sync();status('Source files changed. Audit again before training.');});
window.addEventListener('beforeunload',e=>{if(busy||modelReady||preparedCsv){e.preventDefault();e.returnValue='';}});
